name: Deploy to Vercel and Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint # Ensures linting passes before deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build -- --base=/ # Ensures Vite works properly

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: preview

      - name: Post Preview URL to PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Vercel Preview URL: ${{ steps.vercel.outputs.preview-url }}"
          gh pr comment ${{ github.event.pull_request.number }} --body "🚀 Preview your changes here: ${{ steps.vercel.outputs.preview-url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
